"""PlatformIO pre-build script: gzip everything in web/ into src/generated/web_assets.h.

The dashboard is served straight from flash, so a single firmware upload carries
both the firmware and the UI (no separate LittleFS image to flash).
"""
import gzip
import hashlib
import os

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
except NameError:  # allow running standalone: python tools/embed_web.py
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WEB_DIR = os.path.join(PROJECT_DIR, "web")
OUT_DIR = os.path.join(PROJECT_DIR, "src", "generated")
OUT_FILE = os.path.join(OUT_DIR, "web_assets.h")

MIME = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript",
    ".css": "text/css",
    ".svg": "image/svg+xml",
    ".json": "application/json",
    ".ico": "image/x-icon",
    ".png": "image/png",
}


def ident(path):
    return "asset_" + "".join(c if c.isalnum() else "_" for c in path)


def build():
    files = []
    for root, _, names in os.walk(WEB_DIR):
        for name in sorted(names):
            full = os.path.join(root, name)
            rel = os.path.relpath(full, WEB_DIR).replace(os.sep, "/")
            ext = os.path.splitext(name)[1].lower()
            if ext not in MIME:
                continue
            with open(full, "rb") as f:
                raw = f.read()
            files.append((rel, MIME[ext], gzip.compress(raw, 9, mtime=0)))

    digest = hashlib.sha1(b"".join(f[2] for f in files)).hexdigest()[:12]
    lines = [
        "// Generated by tools/embed_web.py - do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f'#define WEB_ASSETS_ETAG "\\"{digest}\\""',
        "",
        "struct WebAsset { const char *path; const char *mime; const uint8_t *data; size_t len; };",
        "",
    ]
    for rel, _, data in files:
        lines.append(f"static const uint8_t {ident(rel)}[] = {{")
        for i in range(0, len(data), 24):
            lines.append("  " + ",".join(str(b) for b in data[i:i + 24]) + ",")
        lines.append("};")
    lines.append("")
    lines.append("static const WebAsset WEB_ASSETS[] = {")
    for rel, mime, data in files:
        lines.append(f'  {{"/{rel}", "{mime}", {ident(rel)}, {len(data)}}},')
    lines.append("};")
    lines.append(f"static const size_t WEB_ASSET_COUNT = {len(files)};")
    out = "\n".join(lines) + "\n"

    os.makedirs(OUT_DIR, exist_ok=True)
    old = None
    if os.path.exists(OUT_FILE):
        with open(OUT_FILE, "r", encoding="utf-8") as f:
            old = f.read()
    if old != out:
        with open(OUT_FILE, "w", encoding="utf-8") as f:
            f.write(out)
        print(f"embed_web: wrote {len(files)} assets ({sum(len(f[2]) for f in files)} bytes gz)")


build()
